### ISSUE TITLE
สวัสดีครับ จาร app

### ISSUE THREAD

**Issue by pattaphol** [appcorner/stupid_bot#1]
ผม Takeoff Coder จาก Line Open Chat ห้อง Stupid นะครับ อยากจะขอ Contract หน่อยครับจาร พอดีมีเรื่องจะปรึกษา

**Comment by appcorner** [comment]
email ชื่อนี้ ที่ @gmail.com ได้เลยครับ

**Comment by pattaphol** [comment]
ติดต่อไปแล้วครับจาร
